-   repo: https://github.com/awebdeveloper/pre-commit-prettier
    sha: v0.0.1
    hooks:
    -   id: prettier
-   repo: https://github.com/luizribeiro/pre-commit-mypy
    sha: 0.5.2
    hooks:
    -   id: mypy
        args: [--version]
