-   repo: https://github.com/awebdeveloper/pre-commit-prettier
    sha: v0.0.1
    hooks:
    -   id: prettier
-   repo: https://github.com/d1ff/pre-commit-mypy
    sha: v0.4.1
    hooks:
    -   id: mypy
