language: python

python:
  - "3.6"

env:
  global:
    - DJANGO_SETTINGS_MODULE="gettingstarted.settings"
    - PYTHONPATH="/home/travis/build/luizribeiro/django-settings"
    - PIP_USE_MIRRORS=true
    - BUILD_ON_TRAVIS=true

install:
  - pip install -r requirements.txt

script:
  - python manage.py test
