language: python

python:
  - "3.6"

env:
  global:
    - DJANGO_SETTINGS_MODULE="conf.settings"
    - PYTHONPATH="/home/travis/build/luizribeiro/django-settings"
    - PIP_USE_MIRRORS=true
    - BUILD_ON_TRAVIS=true

install:
  - pip install -r requirements.txt
  - pip install coveralls mypy

script:
  - mypy .
  - coverage run --source=./ manage.py test

after_success:
  - coveralls
