language: python

python:
  - "3.6"

env:
  global:
    - DJANGO_SETTINGS_MODULE="conf.settings.production"
    - PYTHONPATH="/home/travis/build/luizribeiro/django-settings"
    - PIP_USE_MIRRORS=true
    - BUILD_ON_TRAVIS=true

install:
  - pip install -r dev-requirements.txt
  - pip install coveralls

script:
  - mypy .
  - rm .pyre_configuration
  - pyre -l .pyre_configuration.travis check
  - coverage run --source=./ manage.py test

after_success:
  - coveralls
