# Generated by Django 2.0.5 on 2018-05-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribedUser',
            fields=[
                ('user_psid', models.CharField(max_length=22, primary_key=True, serialize=False)),
            ],
        ),
    ]
